name = input("Enter Your Name: ")
branch = input("Enter Your Branch: ")
gender = input("Enter Your Gender: ")
collegeName = input("Enter Your College Name: ")
age = int(input("Enter Your Age: "))#age is always in interger(type cast here)
print("Name:",name)
print("Branch:",branch)
print("Gender:",gender)
print("College Name:",collegeName)
print("Age:",age)
