Batsman1=int(input("Enter the Run made by first player in 60 balls"))
Batsman2=int(input("Enter the Run made by Second player in 60 balls"))
Batsman3=int(input("Enter the Run made by Third player in 60 balls"))
print("Strike rate of first player",Batsman1*100/60)
print("Strike rate of first player",Batsman2*100/60)
print("Strike rate of first player",Batsman3*100/60)
print("Runs scored by player 1 if they played 60 balls more ",Batsman1*2)
print("Runs scored by player 1 if they played 60 balls more ",Batsman2*2)
print("Runs scored by player 1 if they played 60 balls more ",Batsman3*2)
print("maximum number of sixes hit by first player",Batsman1//6)
print("maximum number of sixes hit by Second player",Batsman2//6)
print("maximum number of sixes hit by third  player",Batsman3//6)
